matDir = ('/Users/Shared/FCTD/MAT/');


FCTD_hourly_timer = timer;
FCTD_hourly_timer_Stop = false;
FCTD_hourly_timer.StartFcn = 'disp(''Producing hourly data!'');';
FCTD_hourly_timer.TimerFcn = [...
    'if FCTD_hourly_timer_Stop, '...
    'stop(FCTD_hourly_timer); '...
    'delete(FCTD_hourly_timer); '...
    'else, '...
    'try,'...
    'FastCTD_produce_hourly_2019;'...
    'catch err,'...
    'disp(err);'...
    'end;'...
    'disp(''Done'');'...
    'end;'];
FCTD_hourly_timer.Period = 1800;
FCTD_hourly_timer.BusyMode = 'drop';
FCTD_hourly_timer.Name = 'FCTD_hourly_timer';
FCTD_hourly_timer.Tag = 'FCTD_hourly_timer';
FCTD_hourly_timer.StopFcn = 'clear(''rawDir'',''rawDirAway''); disp([datestr(now) '': Stopped FCTD_hourly_timer'']);';
FCTD_hourly_timer.ExecutionMode = 'fixedSpacing';
% FCTD_hourly_timer.ExecutionMode = 'singleShot';
FCTD_hourly_timer.TasksToExecute = Inf;
FCTD_hourly_timer.ErrorFcn = 'disp(''%%%%%%%%%%%%% Error %%%%%%%%%%%%%'');';

start(FCTD_hourly_timer);