function [Profile] = sort_profile(Profile);

% Standard order for Profile structure
fieldOrder = {'profNum';...
              'filenames';...
              'Meta_Data';...
              'varInfo';...
              'epsi';...
              'ctd';...
              'alt';...
              'act';...
              'apf';...
              'vnav';...
              'gps';...
              'seg';...
              'spec';...
              'latitude';...
              'longitude';...
              'nbscan';...
              'nfft';...
              'nfftc';...
              'tscan';...
              'fpump';...
              'f';...
              'k';...
              'dnum';...
              'pr';...
              'z';...
              'w';...
              't';...
              's';...
              'th';...
              'sgth';...
              'pitch';...
              'roll';...
              'kvis';...
              'ind_range_ctd';...
              'ind_range_epsi';...
              'epsilon';...
              'epsilon_co';...
              'epsilon_method';...
              'epsilon_final';...
              'epsi_qc';...
              'qc';...
              'sh_fc';...
              'sh_kc';...
              'chi';...
              'tg_fc';...
              'tg_kc';...
              'flag_tg_fc';...
              'fom';...
              'avgspec';...
              'dissrate';...
              'calib_volt';...
              'calib_vel';...
              'Ps_volt_f';...
              'Ps_velocity_f';...
              'Ps_shear_k';...
              'Ps_shear_co_k';...
              'Pt_volt_f';...
              'Pt_Tg_k';...
              'Pa_g_f';...
              'Cs1a3';...
              'Cs2a3';...
              'sumPa';...
              'ttv'};
          
 % Find the field names in Profile
 fieldNames = fields(Profile);
 
 % Find the fields in fieldOrder that also exist in fieldNames. Only keep
 % those. 
commonFields = fieldOrder(ismember(fieldOrder,fieldNames));

% Sort Profile in the order of commonFields
try
    Profile = orderfields(Profile,commonFields);
catch
    disp("l.79 sort_profile.m : orderfields does not have all the fields names. NOT A PROBLEM.")
end
          
end